"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import Head from "next/head";

const Metadata = () => {
  const pathname = usePathname();
  const isPlatformRoute = pathname && pathname.includes("/platform");
  const isControlCenterRoute = pathname && pathname.includes("/control_center");
  const brandName = process.env.NEXT_PUBLIC_BRAND_NAME;

  useEffect(() => {
    if (isPlatformRoute) {
      document.title = `${brandName} | Campus Virtual`;
    } else if (isControlCenterRoute) {
      document.title = `${brandName} | Centro de Control`;
    } else {
      document.title = brandName;
    }
  }, [isPlatformRoute, isControlCenterRoute, brandName]);

  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
};

export default Metadata;
