"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import Head from "next/head";

const Metadata = () => {
  const pathname = usePathname();
  const isTournamentRoute = pathname && pathname.includes("/tournaments");
  const brandName = process.env.NEXT_PUBLIC_BRAND_NAME || "Empresa";

  useEffect(() => {
    if (isTournamentRoute) {
      document.title = `${brandName} | Torneos de Ajedrez`;
    } else {
      document.title = brandName;
    }
  }, [isTournamentRoute, brandName]);

  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.svg" sizes="any" type="image/svg+xml" />
    </Head>
  );
};

export default Metadata;
